### ISSUE TITLE
Некорректная проверка cookie параметров

### ISSUE THREAD

**Issue by BlackFan** [beched/BurpArgsFind#1]
При проверке cookie параметров пейлоад добавляется и в cookie и в тело запроса.

![screenshot at 14-47-22](https://user-images.githubusercontent.com/3295867/32220237-6dec17ec-be4a-11e7-84c8-66a13ec8f4ff.png)

**Comment by beched** [comment]
Думаю, что пофиксил:
https://github.com/beched/BurpArgsFind/commit/6593c66200db4b6764c9240c1841cb6f753c3d87
https://github.com/beched/BurpArgsFind/commit/7e125525947c2e735ed2a5e1988138ce43bcd3cf
